/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * VerdanTech-Backend
 * Backend API of the VerdanTech software project.
 * OpenAPI spec version: 0.1.0
 */
export type UserCreate400ExtraAnyOf = { [key: string]: any };

export type UserCreate400Extra = null | UserCreate400ExtraAnyOf | unknown[];

/**
 * Validation Exception
 */
export type UserCreate400 = {
	detail: string;
	extra?: UserCreate400Extra;
	status_code: number;
};

export type UserPasswordResetRequest400ExtraAnyOf = { [key: string]: any };

export type UserPasswordResetRequest400Extra =
	| null
	| UserPasswordResetRequest400ExtraAnyOf
	| unknown[];

/**
 * Validation Exception
 */
export type UserPasswordResetRequest400 = {
	detail: string;
	extra?: UserPasswordResetRequest400Extra;
	status_code: number;
};

export type UserPasswordResetConfirm400ExtraAnyOf = { [key: string]: any };

export type UserPasswordResetConfirm400Extra =
	| null
	| UserPasswordResetConfirm400ExtraAnyOf
	| unknown[];

/**
 * Validation Exception
 */
export type UserPasswordResetConfirm400 = {
	detail: string;
	extra?: UserPasswordResetConfirm400Extra;
	status_code: number;
};

export type UserEmailVerificationRequest422ExtraAnyOf = { [key: string]: any };

export type UserEmailVerificationRequest422Extra =
	| null
	| UserEmailVerificationRequest422ExtraAnyOf
	| unknown[];

/**
 * Client Error
 */
export type UserEmailVerificationRequest422 = {
	detail: string;
	extra?: UserEmailVerificationRequest422Extra;
	status_code: number;
};

export type UserEmailVerificationRequest400ExtraAnyOf = { [key: string]: any };

export type UserEmailVerificationRequest400Extra =
	| null
	| UserEmailVerificationRequest400ExtraAnyOf
	| unknown[];

/**
 * Validation Exception
 */
export type UserEmailVerificationRequest400 = {
	detail: string;
	extra?: UserEmailVerificationRequest400Extra;
	status_code: number;
};

export type UserEmailConfirmationConfirm422ExtraAnyOf = { [key: string]: any };

export type UserEmailConfirmationConfirm422Extra =
	| null
	| UserEmailConfirmationConfirm422ExtraAnyOf
	| unknown[];

/**
 * Client Error
 */
export type UserEmailConfirmationConfirm422 = {
	detail: string;
	extra?: UserEmailConfirmationConfirm422Extra;
	status_code: number;
};

export type UserEmailConfirmationConfirm400ExtraAnyOf = { [key: string]: any };

export type UserEmailConfirmationConfirm400Extra =
	| null
	| UserEmailConfirmationConfirm400ExtraAnyOf
	| unknown[];

/**
 * Validation Exception
 */
export type UserEmailConfirmationConfirm400 = {
	detail: string;
	extra?: UserEmailConfirmationConfirm400Extra;
	status_code: number;
};

export type UserProfiles400ExtraAnyOf = { [key: string]: any };

export type UserProfiles400Extra = null | UserProfiles400ExtraAnyOf | unknown[];

/**
 * Validation Exception
 */
export type UserProfiles400 = {
	detail: string;
	extra?: UserProfiles400Extra;
	status_code: number;
};

export type UserProfiles200 = UserPublicSchema[] | UserFullSchema;

export type UserLogin400ExtraAnyOf = { [key: string]: any };

export type UserLogin400Extra = null | UserLogin400ExtraAnyOf | unknown[];

/**
 * Validation Exception
 */
export type UserLogin400 = {
	detail: string;
	extra?: UserLogin400Extra;
	status_code: number;
};

export type GardenCreate400ExtraAnyOf = { [key: string]: any };

export type GardenCreate400Extra = null | GardenCreate400ExtraAnyOf | unknown[];

/**
 * Validation Exception
 */
export type GardenCreate400 = {
	detail: string;
	extra?: GardenCreate400Extra;
	status_code: number;
};

export type GardenRevoke400ExtraAnyOf = { [key: string]: any };

export type GardenRevoke400Extra = null | GardenRevoke400ExtraAnyOf | unknown[];

/**
 * Validation Exception
 */
export type GardenRevoke400 = {
	detail: string;
	extra?: GardenRevoke400Extra;
	status_code: number;
};

export type GardenLeave400ExtraAnyOf = { [key: string]: any };

export type GardenLeave400Extra = null | GardenLeave400ExtraAnyOf | unknown[];

/**
 * Validation Exception
 */
export type GardenLeave400 = {
	detail: string;
	extra?: GardenLeave400Extra;
	status_code: number;
};

export type GardenLeaveParams = {
	garden_key: string;
};

export type GardenInvite400ExtraAnyOf = { [key: string]: any };

export type GardenInvite400Extra = null | GardenInvite400ExtraAnyOf | unknown[];

/**
 * Validation Exception
 */
export type GardenInvite400 = {
	detail: string;
	extra?: GardenInvite400Extra;
	status_code: number;
};

export type GardenChange400Extra = null | GardenChange400ExtraAnyOf | unknown[];

/**
 * Validation Exception
 */
export type GardenChange400 = {
	detail: string;
	extra?: GardenChange400Extra;
	status_code: number;
};

export type GardenChange400ExtraAnyOf = { [key: string]: any };

export type GardenAcceptInvite400ExtraAnyOf = { [key: string]: any };

export type GardenAcceptInvite400Extra = null | GardenAcceptInvite400ExtraAnyOf | unknown[];

/**
 * Validation Exception
 */
export type GardenAcceptInvite400 = {
	detail: string;
	extra?: GardenAcceptInvite400Extra;
	status_code: number;
};

export type GardenAcceptInviteParams = {
	garden_key: string;
};

export type GardenAttributesSet400ExtraAnyOf = { [key: string]: any };

export type GardenAttributesSet400Extra = null | GardenAttributesSet400ExtraAnyOf | unknown[];

/**
 * Validation Exception
 */
export type GardenAttributesSet400 = {
	detail: string;
	extra?: GardenAttributesSet400Extra;
	status_code: number;
};

export interface UserVerifyEmailRequestInput {
	email_address: string;
}

export interface UserVerifyEmailConfirmInput {
	key: string;
}

export interface UserPublicSchema {
	/** Any UUID string */
	id: string;
	username: string;
}

export interface UserPasswordResetRequestInput {
	email_address: string;
}

export interface UserPasswordResetConfirmInput {
	key: string;
	new_password1: string;
	new_password2: string;
	user_id: unknown;
}

export interface UserLoginInput {
	email_address: string;
	password: string;
}

export type UserFullSchemaCreatedAt = null | string;

export interface UserFullSchema {
	created_at?: UserFullSchemaCreatedAt;
	emails: EmailSchema[];
	/** Any UUID string */
	id: string;
	is_superuser: boolean;
	username: string;
}

export interface UserCreateInput {
	email_address: string;
	password1: string;
	password2: string;
	username: string;
}

export interface GeoCoordinateProfile {
	lat: number;
	long: number;
}

export type GardenRoleChangeInputRole =
	(typeof GardenRoleChangeInputRole)[keyof typeof GardenRoleChangeInputRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GardenRoleChangeInputRole = {
	admin: 'admin',
	editor: 'editor',
	viewer: 'viewer'
} as const;

export interface GardenRoleChangeInput {
	garden_key: string;
	role: GardenRoleChangeInputRole;
	user_username: string;
}

export interface GardenRevokeMembershipInput {
	garden_key: string;
	user_username: string;
}

export interface GardenRef {
	/** Any UUID string */
	id: string;
	key: string;
}

export type GardenMembershipPublicSchemaRole =
	(typeof GardenMembershipPublicSchemaRole)[keyof typeof GardenMembershipPublicSchemaRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GardenMembershipPublicSchemaRole = {
	admin: 'admin',
	editor: 'editor',
	viewer: 'viewer'
} as const;

export type GardenMembershipPublicSchemaGardenRef = null | GardenRef;

export interface GardenMembershipPublicSchema {
	created_at: string;
	garden_ref?: GardenMembershipPublicSchemaGardenRef;
	role: GardenMembershipPublicSchemaRole;
	user: UserPublicSchema;
}

export type GardenMembershipFullSchemaRole =
	(typeof GardenMembershipFullSchemaRole)[keyof typeof GardenMembershipFullSchemaRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GardenMembershipFullSchemaRole = {
	admin: 'admin',
	editor: 'editor',
	viewer: 'viewer'
} as const;

export type GardenMembershipFullSchemaInviter = null | UserPublicSchema;

export type GardenMembershipFullSchemaGardenRef = null | GardenRef;

export interface GardenMembershipFullSchema {
	created_at: string;
	favorite: boolean;
	garden_ref?: GardenMembershipFullSchemaGardenRef;
	inviter?: GardenMembershipFullSchemaInviter;
	open_invite: boolean;
	role: GardenMembershipFullSchemaRole;
	user: UserPublicSchema;
}

export type GardenInviteCreateInputRole =
	(typeof GardenInviteCreateInputRole)[keyof typeof GardenInviteCreateInputRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GardenInviteCreateInputRole = {
	admin: 'admin',
	editor: 'editor',
	viewer: 'viewer'
} as const;

export interface GardenInviteCreateInput {
	garden_key: string;
	role: GardenInviteCreateInputRole;
	user_username: string;
}

export type GardenFullSchemaVisibility =
	(typeof GardenFullSchemaVisibility)[keyof typeof GardenFullSchemaVisibility];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GardenFullSchemaVisibility = {
	private: 'private',
	unlisted: 'unlisted',
	public: 'public'
} as const;

export type GardenFullSchemaCreator = null | UserPublicSchema;

export interface GardenFullSchema {
	attributes: EnvironmentAttributeCluster;
	creator?: GardenFullSchemaCreator;
	description: string;
	/** Any UUID string */
	id: string;
	key: string;
	memberships: GardenMembershipPublicSchema[];
	name: string;
	num_memberships: number;
	visibility: GardenFullSchemaVisibility;
}

export type GardenCreateInputVisibility =
	(typeof GardenCreateInputVisibility)[keyof typeof GardenCreateInputVisibility];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GardenCreateInputVisibility = {
	private: 'private',
	unlisted: 'unlisted',
	public: 'public'
} as const;

export interface GardenCreateInput {
	admin_usernames?: string[];
	description?: string;
	editor_usernames?: string[];
	name: string;
	viewer_usernames?: string[];
	visibility?: GardenCreateInputVisibility;
}

export interface FrostDateProfile {
	first_frost_date: string;
	last_frost_date: string;
}

export type EnvironmentAttributeClusterInputProfilesItem = FrostDateProfile | GeoCoordinateProfile;

export interface EnvironmentAttributeClusterInput {
	profiles: EnvironmentAttributeClusterInputProfilesItem[];
}

export type EnvironmentAttributeClusterGeoCoordinateProfile = null | GeoCoordinateProfile;

export type EnvironmentAttributeClusterFrostDateProfile = null | FrostDateProfile;

export interface EnvironmentAttributeCluster {
	frost_date_profile?: EnvironmentAttributeClusterFrostDateProfile;
	geo_coordinate_profile?: EnvironmentAttributeClusterGeoCoordinateProfile;
}

export interface EmailSchema {
	address: string;
	primary: boolean;
	verified: boolean;
}
