/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * VerdanTech-Backend
 * OpenAPI spec version: 0.1.0
 */
/**
 * Validation Exception
 */
export type VdtapiUsersWriteCreateUserCreate400 = { [key: string]: any };

/**
 * Validation Exception
 */
export type VdtapiUsersVerificationPasswordRequestUserPasswordResetRequest400 = { [key: string]: any };

/**
 * Validation Exception
 */
export type VdtapiUsersVerificationPasswordConfirmUserPasswordResetConfirm400 = { [key: string]: any };

/**
 * Validation Exception
 */
export type VdtapiUsersVerificationEmailVerificationRequestUserEmailConfirmationRequest400 = { [key: string]: any };

/**
 * Validation Exception
 */
export type VdtapiUsersVerificationEmailVerificationConfirmUserEmailConfirmationConfirm400 = { [key: string]: any };

export interface UserVerifyEmailRequestInput {
  email_address: string;
}

export interface UserVerifyEmailConfirmInput {
  key: string;
}

export interface UserPasswordResetRequestInput {
  email_address: string;
}

export type UserPasswordResetConfirmInputUserId = { [key: string]: any };

export interface UserPasswordResetConfirmInput {
  key: string;
  new_password1: string;
  new_password2: string;
  user_id: UserPasswordResetConfirmInputUserId;
}

export type UserCreateUser0ResponseBodyVerifiedAt = null | string;

export type UserCreateUser0ResponseBodyConfirmation = null | UserCreateEmail0ResponseBody;

export interface UserCreateUser0ResponseBody {
  address: string;
  confirmation?: UserCreateUser0ResponseBodyConfirmation;
  primary?: boolean;
  verified?: boolean;
  verified_at?: UserCreateUser0ResponseBodyVerifiedAt;
}

export type UserCreateUserResponseBodyIdOneOf = { [key: string]: any };

export type UserCreateUserResponseBodyId = null | UserCreateUserResponseBodyIdOneOf;

export interface UserCreateUserResponseBody {
  created_at?: string;
  emails?: UserCreateUser0ResponseBody[];
  id?: UserCreateUserResponseBodyId;
  is_superuser?: boolean;
  username: string;
}

export interface UserCreateInput {
  email_address: string;
  password1: string;
  password2: string;
  username: string;
}

export interface UserCreateEmail0ResponseBody {
  created_at?: string;
  key: string;
}

